package com.ge.research.sadl.darpa.aske.rest.grasen.service;

import static org.hamcrest.Matchers.containsString;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

/**
 * Checks that the application's REST endpoint can receive a JSON file
 * and will return a SADL file generated from the JSON file.
 *
 * Also checks that the application's REST endpoint has Swagger UI
 * documentation.
 */
@SpringBootTest
@AutoConfigureMockMvc
public class GrasenControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    public void shouldDisplaySwaggerUiPage() throws Exception {
        mockMvc.perform(get("/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config"))
                .andExpect(status().isOk())
                .andExpect(content().string(containsString("Swagger")));
    }

    @Test
    public void translateShouldReturnFile() throws Exception {
        String jsonContent =
                "{'grfn' : {\n"
                + "  \"uid\": \"ebe21368-98c7-5205-1e01-a934402d0baf\",\n"
                + "  \"entry_point\": \"@container::GE_simple_PI_controller::GE_simple_PI_controller::GE_simple_PI_controller.main\",\n"
                + "  \"timestamp\": \"2021-05-14\",\n"
                + "  \"hyper_edges\": [\n"
                + "    {\n"
                + "      \"inputs\": [\n"
                + "        \"f728b4fa-4248-5e3a-0a5d-2f346baa9455\",\n"
                + "        \"eb1167b3-67a9-c378-7c65-c1e582e2e662\"\n"
                + "      ],\n"
                + "      \"function\": \"ba26d851-35e8-579a-7aaf-0e891fb797fa\",\n"
                + "      \"outputs\": [\n"
                + "        \"1846d424-c17c-6279-23c6-612f48268673\"\n"
                + "      ]\n"
                + "    }\n"
                + "  ],\n"
                + "  \"variables\": [\n"
                + "    {\n"
                + "      \"uid\": \"f728b4fa-4248-5e3a-0a5d-2f346baa9455\",\n"
                + "      \"identifier\": \"GE_simple_PI_controller::GE_simple_PI_controller.PI_calc::Input_dmd::-1\",\n"
                + "      \"object_ref\": null,\n"
                + "      \"metadata\": [\n"
                + "        {\n"
                + "          \"type\": \"domain\",\n"
                + "          \"provenance\": {\n"
                + "            \"method\": \"program_analysis_pipeline\",\n"
                + "            \"timestamp\": \"2021-05-14 16:28:20.565330\"\n"
                + "          },\n"
                + "          \"data_type\": \"integer\",\n"
                + "          \"measurement_scale\": \"discrete\",\n"
                + "          \"elements\": []\n"
                + "        },\n"
                + "        {\n"
                + "          \"type\": \"from_source\",\n"
                + "          \"provenance\": {\n"
                + "             \"method\": \"program_analysis_pipeline\",\n"
                + "             \"timestamp\": \"2021-06-09 09:29:08.671742\"\n"
                + "          },\n"
                + "          \"from_source\": \"True\",\n"
                + "          \"creation_reason\": \"UNKNOWN\"\n"
                + "        },\n"
                + "        {\n"
                + "          \"type\": \"code_span_reference\",\n"
                + "          \"provenance\": {\n"
                + "            \"method\": \"program_analysis_pipeline\",\n"
                + "            \"timestamp\": \"2021-05-14 16:28:20.563284\"\n"
                + "          },\n"
                + "          \"code_type\": \"identifier\",\n"
                + "          \"code_file_reference_uid\": \"\",\n"
                + "          \"code_span\": {\n"
                + "            \"line_begin\": 8,\n"
                + "            \"line_end\": null,\n"
                + "            \"col_begin\": 23,\n"
                + "            \"col_end\": null\n"
                + "          }\n"
                + "        }\n"
                + "      ]\n"
                + "    }\n"
                + "  ],\n"
                + "  \"functions\": [\n"
                + "    {\n"
                + "      \"uid\": \"ba26d851-35e8-579a-7aaf-0e891fb797fa\",\n"
                + "      \"type\": \"ASSIGN\",\n"
                + "      \"lambda\": \"lambda Input_dmd,Input_sensed: (Input_dmd - Input_sensed)\",\n"
                + "      \"metadata\": [\n"
                + "        {\n"
                + "          \"type\": \"code_span_reference\",\n"
                + "          \"provenance\": {\n"
                + "            \"method\": \"program_analysis_pipeline\",\n"
                + "            \"timestamp\": \"2021-05-14 16:28:20.564182\"\n"
                + "          },\n"
                + "          \"code_type\": \"block\",\n"
                + "          \"code_file_reference_uid\": \"\",\n"
                + "          \"code_span\": {\n"
                + "            \"line_begin\": 10,\n"
                + "            \"line_end\": null,\n"
                + "            \"col_begin\": 12,\n"
                + "            \"col_end\": null\n"
                + "          }\n"
                + "        }\n"
                + "      ]\n"
                + "    }\n"
                + "  ],\n"
                + "  \"subgraphs\": [\n"
                + "    {\n"
                + "      \"uid\": \"31d0b664-0589-f877-9b02-52440950fd13\",\n"
                + "      \"namespace\": \"GE_simple_PI_controller\",\n"
                + "      \"scope\": \"GE_simple_PI_controller\",\n"
                + "      \"basename\": \"GE_simple_PI_controller.PI_calc\",\n"
                + "      \"occurrence_num\": 1,\n"
                + "      \"parent\": \"176ea1b1-6426-4cd5-1ea4-5cd69371a71f\",\n"
                + "      \"type\": \"FuncContainer\",\n"
                + "      \"border_color\": \"forestgreen\",\n"
                + "      \"nodes\": [\n"
                + "        \"f728b4fa-4248-5e3a-0a5d-2f346baa9455\",\n"
                + "        \"ba26d851-35e8-579a-7aaf-0e891fb797fa\"\n"
                + "      ],\n"
                + "      \"metadata\": [\n"
                + "        {\n"
                + "          \"type\": \"code_span_reference\",\n"
                + "          \"provenance\": {\n"
                + "            \"method\": \"program_analysis_pipeline\",\n"
                + "            \"timestamp\": \"2021-05-14 16:28:20.564255\"\n"
                + "          },\n"
                + "          \"code_type\": \"block\",\n"
                + "          \"code_file_reference_uid\": \"\",\n"
                + "          \"code_span\": {\n"
                + "            \"line_begin\": 9,\n"
                + "            \"line_end\": 15,\n"
                + "            \"col_begin\": null,\n"
                + "            \"col_end\": null\n"
                + "          }\n"
                + "        }\n"
                + "      ]\n"
                + "    }\n"
                + "  ]\n"
                + "},"
                + "'expTree' : []"
                + "}";
        
        String simple_stmts_json = "{\n"
        		+ "  \"grfn\": {\n"
        		+ "    \"entry_point\": \"@container::simple_stmts::simple_stmts::simple_stmts.main\",\n"
        		+ "    \"functions\": [\n"
        		+ "      {\n"
        		+ "        \"lambda\": \"lambda : -1\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": null,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": null,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"block\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006945\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"type\": \"LITERAL\",\n"
        		+ "        \"uid\": \"2a131d68-eec5-7143-b1c8-7e314019a565\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"lambda\": \"lambda : -1\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": null,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": null,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"block\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006957\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"type\": \"LITERAL\",\n"
        		+ "        \"uid\": \"a9fbde1a-5e12-7a3c-d8a4-563418a5a4ee\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"lambda\": \"lambda a,b: (a + b)\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": 5,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": 7,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"block\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006968\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"type\": \"ASSIGN\",\n"
        		+ "        \"uid\": \"83b2ec74-19db-64d3-8332-fb7886edb824\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"lambda\": \"lambda b,c: (b + c)\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": 5,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": 9,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"block\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006979\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"type\": \"ASSIGN\",\n"
        		+ "        \"uid\": \"6c8353e9-568a-013e-05be-9dc82a387d78\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"lambda\": \"lambda : 0\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": 1,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": 10,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"block\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006987\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"type\": \"LITERAL\",\n"
        		+ "        \"uid\": \"9b682fd9-57f4-9411-cd72-ff1df8352126\"\n"
        		+ "      }\n"
        		+ "    ],\n"
        		+ "    \"hyper_edges\": [\n"
        		+ "      {\n"
        		+ "        \"function\": \"2a131d68-eec5-7143-b1c8-7e314019a565\",\n"
        		+ "        \"inputs\": [],\n"
        		+ "        \"outputs\": [\n"
        		+ "          \"fae64108-bacc-e382-5323-a89ff154fd32\"\n"
        		+ "        ]\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"function\": \"a9fbde1a-5e12-7a3c-d8a4-563418a5a4ee\",\n"
        		+ "        \"inputs\": [],\n"
        		+ "        \"outputs\": [\n"
        		+ "          \"910b11ea-e7a7-d0f9-6de2-5047784a11d2\"\n"
        		+ "        ]\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"function\": \"83b2ec74-19db-64d3-8332-fb7886edb824\",\n"
        		+ "        \"inputs\": [\n"
        		+ "          \"910b11ea-e7a7-d0f9-6de2-5047784a11d2\",\n"
        		+ "          \"fae64108-bacc-e382-5323-a89ff154fd32\"\n"
        		+ "        ],\n"
        		+ "        \"outputs\": [\n"
        		+ "          \"5dff8a39-8827-a0c4-1d3b-94d3976999da\"\n"
        		+ "        ]\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"function\": \"6c8353e9-568a-013e-05be-9dc82a387d78\",\n"
        		+ "        \"inputs\": [\n"
        		+ "          \"fae64108-bacc-e382-5323-a89ff154fd32\",\n"
        		+ "          \"5dff8a39-8827-a0c4-1d3b-94d3976999da\"\n"
        		+ "        ],\n"
        		+ "        \"outputs\": [\n"
        		+ "          \"8f55874a-8a4f-4464-5245-7c09641f89fc\"\n"
        		+ "        ]\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"function\": \"9b682fd9-57f4-9411-cd72-ff1df8352126\",\n"
        		+ "        \"inputs\": [],\n"
        		+ "        \"outputs\": [\n"
        		+ "          \"b1bc890a-d591-9586-aadb-aca7e70c7687\"\n"
        		+ "        ]\n"
        		+ "      }\n"
        		+ "    ],\n"
        		+ "    \"metadata\": [],\n"
        		+ "    \"subgraphs\": [\n"
        		+ "      {\n"
        		+ "        \"basename\": \"simple_stmts.main\",\n"
        		+ "        \"border_color\": \"forestgreen\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": null,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": 4,\n"
        		+ "              \"line_end\": 10\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"block\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006991\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"namespace\": \"simple_stmts\",\n"
        		+ "        \"nodes\": [\n"
        		+ "          \"fae64108-bacc-e382-5323-a89ff154fd32\",\n"
        		+ "          \"2a131d68-eec5-7143-b1c8-7e314019a565\",\n"
        		+ "          \"910b11ea-e7a7-d0f9-6de2-5047784a11d2\",\n"
        		+ "          \"a9fbde1a-5e12-7a3c-d8a4-563418a5a4ee\",\n"
        		+ "          \"5dff8a39-8827-a0c4-1d3b-94d3976999da\",\n"
        		+ "          \"83b2ec74-19db-64d3-8332-fb7886edb824\",\n"
        		+ "          \"8f55874a-8a4f-4464-5245-7c09641f89fc\",\n"
        		+ "          \"6c8353e9-568a-013e-05be-9dc82a387d78\",\n"
        		+ "          \"b1bc890a-d591-9586-aadb-aca7e70c7687\",\n"
        		+ "          \"9b682fd9-57f4-9411-cd72-ff1df8352126\"\n"
        		+ "        ],\n"
        		+ "        \"occurrence_num\": 1,\n"
        		+ "        \"parent\": null,\n"
        		+ "        \"scope\": \"simple_stmts\",\n"
        		+ "        \"type\": \"FuncContainer\",\n"
        		+ "        \"uid\": \"092ef576-d9b0-5a20-673a-7c7dd4137684\"\n"
        		+ "      }\n"
        		+ "    ],\n"
        		+ "    \"timestamp\": \"2021-10-06\",\n"
        		+ "    \"types\": [\n"
        		+ "      {\n"
        		+ "        \"fields\": [\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_flags\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_read_ptr\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_read_end\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_read_base\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_write_base\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_write_ptr\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_write_end\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_buf_base\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_buf_end\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_save_base\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_backup_base\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_IO_save_end\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_markers\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_chain\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_fileno\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_flags2\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_old_offset\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_cur_column\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_vtable_offset\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_shortbuf\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_lock\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_offset\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_codecvt\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_wide_data\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_freeres_list\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_freeres_buf\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"__pad5\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_mode\",\n"
        		+ "            \"type\": \"Number\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"metadata\": [],\n"
        		+ "            \"name\": \"_unused2\",\n"
        		+ "            \"type\": \"List\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"metadata\": [],\n"
        		+ "        \"metatype\": \"composite\",\n"
        		+ "        \"name\": \"_IO_FILE\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"fields\": [],\n"
        		+ "        \"metadata\": [],\n"
        		+ "        \"metatype\": \"composite\",\n"
        		+ "        \"name\": \"_IO_marker\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"fields\": [],\n"
        		+ "        \"metadata\": [],\n"
        		+ "        \"metatype\": \"composite\",\n"
        		+ "        \"name\": \"_IO_codecvt\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"fields\": [],\n"
        		+ "        \"metadata\": [],\n"
        		+ "        \"metatype\": \"composite\",\n"
        		+ "        \"name\": \"_IO_wide_data\"\n"
        		+ "      }\n"
        		+ "    ],\n"
        		+ "    \"uid\": \"7fc85934-238b-f8db-4cbe-ad634ffff4e3\",\n"
        		+ "    \"variables\": [\n"
        		+ "      {\n"
        		+ "        \"identifier\": \"simple_stmts::simple_stmts.main::b::-1\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"data_type\": \"integer\",\n"
        		+ "            \"elements\": [],\n"
        		+ "            \"measurement_scale\": \"discrete\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.007250\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"domain\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"creation_reason\": \"UNKNOWN\",\n"
        		+ "            \"from_source\": \"True\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006592\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"from_source\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": null,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": null,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"identifier\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006760\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"object_ref\": null,\n"
        		+ "        \"uid\": \"fae64108-bacc-e382-5323-a89ff154fd32\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"identifier\": \"simple_stmts::simple_stmts.main::a::-1\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"data_type\": \"integer\",\n"
        		+ "            \"elements\": [],\n"
        		+ "            \"measurement_scale\": \"discrete\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.007304\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"domain\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"creation_reason\": \"UNKNOWN\",\n"
        		+ "            \"from_source\": \"True\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006613\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"from_source\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": null,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": null,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"identifier\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006797\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"object_ref\": null,\n"
        		+ "        \"uid\": \"910b11ea-e7a7-d0f9-6de2-5047784a11d2\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"identifier\": \"simple_stmts::simple_stmts.main::c::0\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"data_type\": \"integer\",\n"
        		+ "            \"elements\": [],\n"
        		+ "            \"measurement_scale\": \"discrete\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.007321\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"domain\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"creation_reason\": \"UNKNOWN\",\n"
        		+ "            \"from_source\": \"True\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006633\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"from_source\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": 5,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": 7,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"identifier\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006818\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"object_ref\": null,\n"
        		+ "        \"uid\": \"5dff8a39-8827-a0c4-1d3b-94d3976999da\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"identifier\": \"simple_stmts::simple_stmts.main::b::0\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"data_type\": \"integer\",\n"
        		+ "            \"elements\": [],\n"
        		+ "            \"measurement_scale\": \"discrete\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.007335\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"domain\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"creation_reason\": \"UNKNOWN\",\n"
        		+ "            \"from_source\": \"True\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006654\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"from_source\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": 5,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": 9,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"identifier\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006838\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"object_ref\": null,\n"
        		+ "        \"uid\": \"8f55874a-8a4f-4464-5245-7c09641f89fc\"\n"
        		+ "      },\n"
        		+ "      {\n"
        		+ "        \"identifier\": \"simple_stmts::simple_stmts.main::RETURN_VAL::-1\",\n"
        		+ "        \"metadata\": [\n"
        		+ "          {\n"
        		+ "            \"data_type\": \"unknown\",\n"
        		+ "            \"elements\": [],\n"
        		+ "            \"measurement_scale\": \"unknown\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.007352\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"domain\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"creation_reason\": \"COMPLEX_RETURN_EXPR\",\n"
        		+ "            \"from_source\": \"False\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.005837\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"from_source\"\n"
        		+ "          },\n"
        		+ "          {\n"
        		+ "            \"code_file_reference_uid\": \"\",\n"
        		+ "            \"code_span\": {\n"
        		+ "              \"col_begin\": 1,\n"
        		+ "              \"col_end\": null,\n"
        		+ "              \"line_begin\": 10,\n"
        		+ "              \"line_end\": null\n"
        		+ "            },\n"
        		+ "            \"code_type\": \"identifier\",\n"
        		+ "            \"provenance\": {\n"
        		+ "              \"method\": \"program_analysis_pipeline\",\n"
        		+ "              \"timestamp\": \"2021-10-06 13:31:39.006856\"\n"
        		+ "            },\n"
        		+ "            \"type\": \"code_span_reference\"\n"
        		+ "          }\n"
        		+ "        ],\n"
        		+ "        \"object_ref\": null,\n"
        		+ "        \"uid\": \"b1bc890a-d591-9586-aadb-aca7e70c7687\"\n"
        		+ "      }\n"
        		+ "    ]\n"
        		+ "  },\n"
        		+ "  \"expTreeArray\": [\n"
        		+ "    {\n"
        		+ "      \"func_node_uid\": \"2a131d68-eec5-7143-b1c8-7e314019a565\",\n"
        		+ "      \"nodes\": [\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"definition\": \"ARGUMENTS\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"a2a4bb84-07b6-a27d-f860-5bfccd49fa27\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"type\": \"VALUE\",\n"
        		+ "          \"uid\": \"f0eb6323-92f3-85a1-8ba0-2eccd80d2bcd\",\n"
        		+ "          \"value\": 1\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"f0eb6323-92f3-85a1-8ba0-2eccd80d2bcd\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"USub\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"a86b6a28-dfee-3898-51a8-6c691691a06d\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"a86b6a28-dfee-3898-51a8-6c691691a06d\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"RETURN\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"ea0447eb-57ab-de00-b9b4-5bca21d2de04\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"a2a4bb84-07b6-a27d-f860-5bfccd49fa27\",\n"
        		+ "            \"ea0447eb-57ab-de00-b9b4-5bca21d2de04\"\n"
        		+ "          ],\n"
        		+ "          \"definition\": \"LAMBDA\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"a3b0f47f-edda-c850-0192-3327608130f8\"\n"
        		+ "        }\n"
        		+ "      ]\n"
        		+ "    },\n"
        		+ "    {\n"
        		+ "      \"func_node_uid\": \"a9fbde1a-5e12-7a3c-d8a4-563418a5a4ee\",\n"
        		+ "      \"nodes\": [\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"definition\": \"ARGUMENTS\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"cab80a90-b8c9-cfdf-4fd6-ede16e5135b3\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"type\": \"VALUE\",\n"
        		+ "          \"uid\": \"7f2e7fa8-14a9-0e5d-a867-31c1b78b4431\",\n"
        		+ "          \"value\": 1\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"7f2e7fa8-14a9-0e5d-a867-31c1b78b4431\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"USub\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"6b23ca50-5060-9def-d28a-257257d20660\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"6b23ca50-5060-9def-d28a-257257d20660\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"RETURN\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"ae24b5ae-4522-7258-864e-e55e98633033\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"cab80a90-b8c9-cfdf-4fd6-ede16e5135b3\",\n"
        		+ "            \"ae24b5ae-4522-7258-864e-e55e98633033\"\n"
        		+ "          ],\n"
        		+ "          \"definition\": \"LAMBDA\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"f87880c5-3f92-2155-9635-0495d8fb1920\"\n"
        		+ "        }\n"
        		+ "      ]\n"
        		+ "    },\n"
        		+ "    {\n"
        		+ "      \"func_node_uid\": \"83b2ec74-19db-64d3-8332-fb7886edb824\",\n"
        		+ "      \"nodes\": [\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"910b11ea-e7a7-d0f9-6de2-5047784a11d2\",\n"
        		+ "          \"identifier\": \"a\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"9c3fa318-1c4b-b789-e294-ccbc43c31d74\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"fae64108-bacc-e382-5323-a89ff154fd32\",\n"
        		+ "          \"identifier\": \"b\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"e48e3834-542a-f8c6-b746-9a8aef3269e6\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"9c3fa318-1c4b-b789-e294-ccbc43c31d74\",\n"
        		+ "            \"e48e3834-542a-f8c6-b746-9a8aef3269e6\"\n"
        		+ "          ],\n"
        		+ "          \"definition\": \"ARGUMENTS\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"5abd9077-b65c-764a-d516-6c7a297ec6a4\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"910b11ea-e7a7-d0f9-6de2-5047784a11d2\",\n"
        		+ "          \"identifier\": \"a\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"8faab09b-5c64-bfd2-4056-9c023a18eda6\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"fae64108-bacc-e382-5323-a89ff154fd32\",\n"
        		+ "          \"identifier\": \"b\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"565461ca-02b4-1d43-85ed-a31673ba1f66\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"8faab09b-5c64-bfd2-4056-9c023a18eda6\",\n"
        		+ "            \"565461ca-02b4-1d43-85ed-a31673ba1f66\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"Add\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"7059fb51-fe71-fab8-984b-c5ac00957267\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"7059fb51-fe71-fab8-984b-c5ac00957267\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"RETURN\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"7bbea4d5-0cb7-6cff-7e90-8d9f1a9f5b61\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"5abd9077-b65c-764a-d516-6c7a297ec6a4\",\n"
        		+ "            \"7bbea4d5-0cb7-6cff-7e90-8d9f1a9f5b61\"\n"
        		+ "          ],\n"
        		+ "          \"definition\": \"LAMBDA\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"276dfe16-1a36-eae5-88ed-c1c890579349\"\n"
        		+ "        }\n"
        		+ "      ]\n"
        		+ "    },\n"
        		+ "    {\n"
        		+ "      \"func_node_uid\": \"6c8353e9-568a-013e-05be-9dc82a387d78\",\n"
        		+ "      \"nodes\": [\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"fae64108-bacc-e382-5323-a89ff154fd32\",\n"
        		+ "          \"identifier\": \"b\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"69173597-a30c-31a8-b867-0111f6ca4755\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"5dff8a39-8827-a0c4-1d3b-94d3976999da\",\n"
        		+ "          \"identifier\": \"c\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"7be162ea-1e2b-a5f9-f034-d43659d59e08\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"69173597-a30c-31a8-b867-0111f6ca4755\",\n"
        		+ "            \"7be162ea-1e2b-a5f9-f034-d43659d59e08\"\n"
        		+ "          ],\n"
        		+ "          \"definition\": \"ARGUMENTS\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"f89dfd12-7073-dfe7-5897-1e688dcc10a7\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"fae64108-bacc-e382-5323-a89ff154fd32\",\n"
        		+ "          \"identifier\": \"b\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"8aca8b20-68fe-2351-035b-86041c37bcbf\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"grfn_uid\": \"5dff8a39-8827-a0c4-1d3b-94d3976999da\",\n"
        		+ "          \"identifier\": \"c\",\n"
        		+ "          \"type\": \"VARIABLE\",\n"
        		+ "          \"uid\": \"11c52f47-4aef-2e35-0eb3-24396a108ef0\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"8aca8b20-68fe-2351-035b-86041c37bcbf\",\n"
        		+ "            \"11c52f47-4aef-2e35-0eb3-24396a108ef0\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"Add\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"0e4fb54f-a2b1-c958-7d84-609ccaf70b57\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"0e4fb54f-a2b1-c958-7d84-609ccaf70b57\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"RETURN\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"18e4551e-64c1-973b-f3cd-21ee352ea9e0\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"f89dfd12-7073-dfe7-5897-1e688dcc10a7\",\n"
        		+ "            \"18e4551e-64c1-973b-f3cd-21ee352ea9e0\"\n"
        		+ "          ],\n"
        		+ "          \"definition\": \"LAMBDA\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"7c6ea9da-4e39-32ad-5588-57616dd660ea\"\n"
        		+ "        }\n"
        		+ "      ]\n"
        		+ "    },\n"
        		+ "    {\n"
        		+ "      \"func_node_uid\": \"9b682fd9-57f4-9411-cd72-ff1df8352126\",\n"
        		+ "      \"nodes\": [\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"definition\": \"ARGUMENTS\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"432c0ed5-65ea-4007-0e27-61aaa3936547\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [],\n"
        		+ "          \"type\": \"VALUE\",\n"
        		+ "          \"uid\": \"87d985d0-8bfa-b8d8-6868-08958258b0fe\",\n"
        		+ "          \"value\": 0\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"87d985d0-8bfa-b8d8-6868-08958258b0fe\"\n"
        		+ "          ],\n"
        		+ "          \"operator\": \"RETURN\",\n"
        		+ "          \"type\": \"OPERATOR\",\n"
        		+ "          \"uid\": \"f906a4f7-b19d-3756-9f0e-7ed4bad2b554\"\n"
        		+ "        },\n"
        		+ "        {\n"
        		+ "          \"children\": [\n"
        		+ "            \"432c0ed5-65ea-4007-0e27-61aaa3936547\",\n"
        		+ "            \"f906a4f7-b19d-3756-9f0e-7ed4bad2b554\"\n"
        		+ "          ],\n"
        		+ "          \"definition\": \"LAMBDA\",\n"
        		+ "          \"type\": \"DEFINITION\",\n"
        		+ "          \"uid\": \"c72cdd9d-fc45-808c-c856-980bea99a404\"\n"
        		+ "        }\n"
        		+ "      ]\n"
        		+ "    }\n"
        		+ "  ]\n"
        		+ "}";
        
        String filename = "simple_stmts.json"; //"test_grfn.json";
        MockMultipartFile mockMultipartFile = new MockMultipartFile("file", filename,
                MediaType.APPLICATION_JSON_VALUE, simple_stmts_json.getBytes());
//        MockMultipartFile mockMultipartFile = new MockMultipartFile("file", filename,
//                MediaType.APPLICATION_JSON_VALUE, PI_json.getBytes());

        MockHttpServletRequestBuilder builder =
                MockMvcRequestBuilders.multipart("/SemanticAnalysis/queryService")
                                      .file(mockMultipartFile);

        try {
            String firstLine = ""; //"uri \"http://grasen.ge.com/simple_stmts\" alias simple_stmts"; //"uri \"http://aske.ge.com/test_grfn\" alias test_grfn";
            mockMvc.perform(builder)
//                .andDo(print())
                .andExpect(status().isOk())
                .andExpect(content().string(containsString(firstLine)));
        }
        catch (org.springframework.web.util.NestedServletException e) {
            e.printStackTrace();
        }
    }   
}
